version: '3.8'

services:
  followstudents:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start", "--", "--host", "0.0.0.0", "--disable-host-check"]
#    command: /bin/bash -c "npm run build-prod && npm start -- --host 0.0.0.0 --disable-host-check"

